# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTittle = QtWidgets.QLabel(self.centralwidget)
        self.lblTittle.setGeometry(QtCore.QRect(250, 20, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTittle.setFont(font)
        self.lblTittle.setObjectName("lblTittle")
        self.txtPlaintext = QtWidgets.QLabel(self.centralwidget)
        self.txtPlaintext.setGeometry(QtCore.QRect(30, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPlaintext.setFont(font)
        self.txtPlaintext.setObjectName("txtPlaintext")
        self.txtKey = QtWidgets.QLabel(self.centralwidget)
        self.txtKey.setGeometry(QtCore.QRect(30, 240, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtKey.setFont(font)
        self.txtKey.setObjectName("txtKey")
        self.txtCiphertext = QtWidgets.QLabel(self.centralwidget)
        self.txtCiphertext.setGeometry(QtCore.QRect(30, 340, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtCiphertext.setFont(font)
        self.txtCiphertext.setObjectName("txtCiphertext")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 110, 481, 101))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 240, 481, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 320, 481, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(230, 440, 93, 28))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(480, 440, 93, 28))
        self.btnDecrypt.setObjectName("btnDecrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTittle.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.txtPlaintext.setText(_translate("MainWindow", "Plaintext:"))
        self.txtKey.setText(_translate("MainWindow", "Key:"))
        self.txtCiphertext.setText(_translate("MainWindow", "Ciphertext:"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
